#!/bin/bash
set -e


#Num  Colour    #define         R G B
#
#0    black     COLOR_BLACK     0,0,0
#1    red       COLOR_RED       1,0,0
#2    green     COLOR_GREEN     0,1,0
#3    yellow    COLOR_YELLOW    1,1,0
#4    blue      COLOR_BLUE      0,0,1
#5    magenta   COLOR_MAGENTA   1,0,1
#6    cyan      COLOR_CYAN      0,1,1
#7    white     COLOR_WHITE     1,1,1

NPM=`which npm`


function printStepTitle() {
    echo "$(tput setab 7) $(tput setaf 4)*** $1 ***$(tput sgr 0)"
}

function printSuccess() {
    echo "$(tput setaf 2)*** $1 ***$(tput sgr 0)"

}
echo "$(tput setab 0) $(tput setaf 3)"
cat << "EOF"

 _________                              __  ____    ____   _
|  _   _  |                            |  ]|_   \  /   _| (_)
|_/ | | \_|_ .--.  .---.  _ .--.   .--.| |   |   \/   |   __   .---.  _ .--.   .--.
    | |   [ `/'`\]/ /__\\[ `.-. |/ /'`\' |   | |\  /| |  [  | / /'`\][ `/'`\]/ .'`\ \
   _| |_   | |    | \__., | | | || \__/  |  _| |_\/_| |_  | | | \__.  | |    | \__. |
  |_____| [___]    '.__.'[___||__]'.__.;__]|_____||_____|[___]'.___.'[___]    '.__.'



EOF

echo "$(tput sgr 0)"
printStepTitle "Running lint script"
"$NPM" run lint

printStepTitle "Running tests"
CI=true "$NPM" run test

printSuccess "Yay! Well done! pushing to git now..."

exit 0
